In [7]:
import pandas as pd
import numpy as np
df=pd.read_csv("clevelanda (1).csv")
df.head(10)

age  gender  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
0   63       1   1       145   233    1        2      150      0      2.3   
1   67       1   4       160   286    0        2      108      1      1.5   
2   67       1   4       120   229    0        2      129      1      2.6   
3   37       1   3       130   250    0        0      187      0      3.5   
4   41       0   2       130   204    0        2      172      0      1.4   
5   56       1   2       120   236    0        0      178      0      0.8   
6   62       0   4       140   268    0        2      160      0      3.6   
7   57       0   4       120   354    0        0      163      1      0.6   
8   63       1   4       130   254    0        2      147      0      1.4   
9   53       1   4       140   203    1        2      155      1      3.1   

   slope ca thal  class  
0      3  0    6      0  
1      2  3    3      2  
2      2  2    7      1  
3      3  0    3      0  
4      1  0    3      0  
5      1  0    3      0  
6      3  2    3      3  
7      1  0    3      0  
8      2  1    7      2  
9      3  0    7      1

In [8]:
df.describe()

age      gender          cp    trestbps        chol         fps  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.438944    0.679868    3.158416  131.689769  246.693069    0.148515   
std      9.038662    0.467299    0.960126   17.599748   51.776918    0.356198   
min     29.000000    0.000000    1.000000   94.000000  126.000000    0.000000   
25%     48.000000    0.000000    3.000000  120.000000  211.000000    0.000000   
50%     56.000000    1.000000    3.000000  130.000000  241.000000    0.000000   
75%     61.000000    1.000000    4.000000  140.000000  275.000000    0.000000   
max     77.000000    1.000000    4.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope       class  
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000  
mean     0.990099  149.607261    0.326733    1.039604    1.600660    0.937294  
std      0.994971   22.875003    0.469794    1.161075    0.616226    1.228536  
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000  
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000  
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000  
75%      2.000000  166.000000    1.000000    1.600000    2.000000    2.000000  
max      2.000000  202.000000    1.000000    6.200000    3.000000    4.000000

In [10]:
df.shape

(303, 14)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   gender    303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fps       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    object 
 12  thal      303 non-null    object 
 13  class     303 non-null    int64  
dtypes: float64(1), int64(11), object(2)
memory usage: 33.3+ KB


In [13]:
df.dtypes

age           int64
gender        int64
cp            int64
trestbps      int64
chol          int64
fps           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca           object
thal         object
class         int64
dtype: object

In [15]:
df.isna().sum()

age         0
gender      0
cp          0
trestbps    0
chol        0
fps         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
class       0
dtype: int64

In [17]:
d_rows = df.duplicated().sum()
d_rows

0

In [18]:
df[:5]

age  gender  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
0   63       1   1       145   233    1        2      150      0      2.3   
1   67       1   4       160   286    0        2      108      1      1.5   
2   67       1   4       120   229    0        2      129      1      2.6   
3   37       1   3       130   250    0        0      187      0      3.5   
4   41       0   2       130   204    0        2      172      0      1.4   

   slope ca thal  class  
0      3  0    6      0  
1      2  3    3      2  
2      2  2    7      1  
3      3  0    3      0  
4      1  0    3      0

In [23]:
df.iloc[:,0:5]

age  gender  cp  trestbps  chol
0     63       1   1       145   233
1     67       1   4       160   286
2     67       1   4       120   229
3     37       1   3       130   250
4     41       0   2       130   204
..   ...     ...  ..       ...   ...
298   45       1   1       110   264
299   68       1   4       144   193
300   57       1   4       130   131
301   57       0   2       130   236
302   38       1   3       138   175

[303 rows x 5 columns]

In [24]:
df['class'].unique()

array([0, 2, 1, 3, 4], dtype=int64)

In [25]:
df[df['class'] == 0].shape[0]

164

In [29]:
df['class'].value_counts()

class
0    164
1     55
2     36
3     35
4     13
Name: count, dtype: int64

In [28]:
pip install plotly

Note: you may need to restart the kernel to use updated packages.


In [32]:
import plotly
import plotly.express as px
fig = px.histogram(df, x='age', y='gender', histfunc='count', title='Histogram of Age vs Gender')
fig.show()

In [33]:
fig = px.histogram(df, x='age', nbins=20, title='Histogram of Age with 20 Bins')
fig.show()

In [38]:
for column in df.columns:
    print(f"Unique values for column '{column}':")
    print(df[column].unique())
    print("\n")

Unique values for column 'age':
[63 67 37 41 56 62 57 53 44 52 48 54 49 64 58 60 50 66 43 40 69 59 42 55
 61 65 71 51 46 45 39 68 47 34 35 29 70 77 38 74 76]


Unique values for column 'gender':
[1 0]


Unique values for column 'cp':
[1 4 3 2]


Unique values for column 'trestbps':
[145 160 120 130 140 172 150 110 132 117 135 112 105 124 125 142 128 170
 155 104 180 138 108 134 122 115 118 100 200  94 165 102 152 101 126 174
 148 178 158 192 129 144 123 136 146 106 156 154 114 164]


Unique values for column 'chol':
[233 286 229 250 204 236 268 354 254 203 192 294 256 263 199 168 239 275
 266 211 283 284 224 206 219 340 226 247 167 230 335 234 177 276 353 243
 225 302 212 330 175 417 197 198 290 253 172 273 213 305 216 304 188 282
 185 232 326 231 269 267 248 360 258 308 245 270 208 264 321 274 325 235
 257 164 141 252 255 201 222 260 182 303 265 309 307 249 186 341 183 407
 217 288 220 209 227 261 174 281 221 205 240 289 318 298 564 246 322 299
 300 293 277 214 207 223 160 394 184 315

In [39]:
df['age'].unique()  #for single column

array([63, 67, 37, 41, 56, 62, 57, 53, 44, 52, 48, 54, 49, 64, 58, 60, 50,
       66, 43, 40, 69, 59, 42, 55, 61, 65, 71, 51, 46, 45, 39, 68, 47, 34,
       35, 29, 70, 77, 38, 74, 76], dtype=int64)

In [41]:
# ? is in ca,thal columns 
df=df.replace('?',np.NaN)
df

age  gender  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
0     63       1   1       145   233    1        2      150      0      2.3   
1     67       1   4       160   286    0        2      108      1      1.5   
2     67       1   4       120   229    0        2      129      1      2.6   
3     37       1   3       130   250    0        0      187      0      3.5   
4     41       0   2       130   204    0        2      172      0      1.4   
..   ...     ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45       1   1       110   264    0        0      132      0      1.2   
299   68       1   4       144   193    1        0      141      0      3.4   
300   57       1   4       130   131    0        0      115      1      1.2   
301   57       0   2       130   236    0        2      174      0      0.0   
302   38       1   3       138   175    0        0      173      0      0.0   

     slope   ca thal  class  
0        3    0    6      0  
1        2    3    3      2  
2        2    2    7      1  
3        3    0    3      0  
4        1    0    3      0  
..     ...  ...  ...    ...  
298      2    0    7      1  
299      2    2    7      2  
300      2    1    7      3  
301      2    1    3      1  
302      1  NaN    3      0  

[303 rows x 14 columns]

In [42]:
for column in df.columns:
    print(f"Unique values for column '{column}':")
    print(df[column].unique())
    print("\n")

Unique values for column 'age':
[63 67 37 41 56 62 57 53 44 52 48 54 49 64 58 60 50 66 43 40 69 59 42 55
 61 65 71 51 46 45 39 68 47 34 35 29 70 77 38 74 76]


Unique values for column 'gender':
[1 0]


Unique values for column 'cp':
[1 4 3 2]


Unique values for column 'trestbps':
[145 160 120 130 140 172 150 110 132 117 135 112 105 124 125 142 128 170
 155 104 180 138 108 134 122 115 118 100 200  94 165 102 152 101 126 174
 148 178 158 192 129 144 123 136 146 106 156 154 114 164]


Unique values for column 'chol':
[233 286 229 250 204 236 268 354 254 203 192 294 256 263 199 168 239 275
 266 211 283 284 224 206 219 340 226 247 167 230 335 234 177 276 353 243
 225 302 212 330 175 417 197 198 290 253 172 273 213 305 216 304 188 282
 185 232 326 231 269 267 248 360 258 308 245 270 208 264 321 274 325 235
 257 164 141 252 255 201 222 260 182 303 265 309 307 249 186 341 183 407
 217 288 220 209 227 261 174 281 221 205 240 289 318 298 564 246 322 299
 300 293 277 214 207 223 160 394 184 315

In [47]:
df.dtypes

age           int64
gender        int64
cp            int64
trestbps      int64
chol          int64
fps           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca           object
thal         object
class         int64
dtype: object

In [49]:
df['ca']=pd.to_numeric(df['ca'],errors='coerce')


In [50]:
df.dtypes

age           int64
gender        int64
cp            int64
trestbps      int64
chol          int64
fps           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca          float64
thal         object
class         int64
dtype: object

In [52]:
df['ca'].describe() #not neccesary

count    299.000000
mean       0.672241
std        0.937438
min        0.000000
25%        0.000000
50%        0.000000
75%        1.000000
max        3.000000
Name: ca, dtype: float64

In [54]:
df['thal']=pd.to_numeric(df['thal'],errors='coerce')
df['thal'].describe()

count    301.000000
mean       4.734219
std        1.939706
min        3.000000
25%        3.000000
50%        3.000000
75%        7.000000
max        7.000000
Name: thal, dtype: float64

In [55]:
df[['ca','thal']].mean()

ca      0.672241
thal    4.734219
dtype: float64

In [69]:
median=df[['ca','thal']].median()
median

ca      0.0
thal    3.0
dtype: float64

In [77]:
mode=df[['ca','thal']].mode()
mode

ca  thal
0  0.0   3.0

In [75]:
df['ca'] = df['ca'].replace('nan',mode)
df

ValueError: Series.replace cannot use dict-value and non-None to_replace

In [73]:
df['thal'] = df['thal'].fillna(3)
df

age  gender  cp  trestbps  chol  fps  restecg  thalach  exang  oldpeak  \
0     63       1   1       145   233    1        2      150      0      2.3   
1     67       1   4       160   286    0        2      108      1      1.5   
2     67       1   4       120   229    0        2      129      1      2.6   
3     37       1   3       130   250    0        0      187      0      3.5   
4     41       0   2       130   204    0        2      172      0      1.4   
..   ...     ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   45       1   1       110   264    0        0      132      0      1.2   
299   68       1   4       144   193    1        0      141      0      3.4   
300   57       1   4       130   131    0        0      115      1      1.2   
301   57       0   2       130   236    0        2      174      0      0.0   
302   38       1   3       138   175    0        0      173      0      0.0   

     slope   ca  thal  class  
0        3  0.0   6.0      0  
1        2  3.0   3.0      2  
2        2  2.0   7.0      1  
3        3  0.0   3.0      0  
4        1  0.0   3.0      0  
..     ...  ...   ...    ...  
298      2  0.0   7.0      1  
299      2  2.0   7.0      2  
300      2  1.0   7.0      3  
301      2  1.0   3.0      1  
302      1  0.0   3.0      0  

[303 rows x 14 columns]

In [78]:
for column in df.columns:
    print(f"Unique values for column '{column}':")
    print(df[column].unique())
    print("\n")

Unique values for column 'age':
[63 67 37 41 56 62 57 53 44 52 48 54 49 64 58 60 50 66 43 40 69 59 42 55
 61 65 71 51 46 45 39 68 47 34 35 29 70 77 38 74 76]


Unique values for column 'gender':
[1 0]


Unique values for column 'cp':
[1 4 3 2]


Unique values for column 'trestbps':
[145 160 120 130 140 172 150 110 132 117 135 112 105 124 125 142 128 170
 155 104 180 138 108 134 122 115 118 100 200  94 165 102 152 101 126 174
 148 178 158 192 129 144 123 136 146 106 156 154 114 164]


Unique values for column 'chol':
[233 286 229 250 204 236 268 354 254 203 192 294 256 263 199 168 239 275
 266 211 283 284 224 206 219 340 226 247 167 230 335 234 177 276 353 243
 225 302 212 330 175 417 197 198 290 253 172 273 213 305 216 304 188 282
 185 232 326 231 269 267 248 360 258 308 245 270 208 264 321 274 325 235
 257 164 141 252 255 201 222 260 182 303 265 309 307 249 186 341 183 407
 217 288 220 209 227 261 174 281 221 205 240 289 318 298 564 246 322 299
 300 293 277 214 207 223 160 394 184 315